name: test workflow to try out act

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: say hello
        run: echo Hello world
      - name: env variables
        run: echo ${{ env.TEST }}

  test-concurrently:
    runs-on: ubuntu-latest

    steps:
      - name: say hello concurrently
        run: echo Hello world concurrently

  try-actions:
    runs-on: ubuntu-latest

    steps:
      - name: try action
        uses: actions/github-script@v6
        with:
          script: console.log('hello world in javascript')

  test-after:
    runs-on: ubuntu-latest
    needs:
      - test
      - test-concurrently

    steps:
      - name: say hello at the end
        run: echo Hello world at the end
